### ISSUE TITLE
Version 1.7.3 removed from maven central

### ISSUE THREAD

**Issue by julianSelser** [asbachb/ftp4j#6]
Hey!

Nice job on the library, we are using it in production for stuff and it works great

We noticed (via maven complaining) that version 1.7.3 is not available in maven central

While we can fix it on our nexus, I just wanted to let you know

Thanks for the nice lib

**Comment by asbachb** [comment]
Hi Julian

first of all I want to clarify that I did not write the library. I just did some minor modifications and published it to GitHub. So basically the thanks should go to the author.

Since the complex release process 1.7.3 was never published to maven central. Normally adding GitHub as maven repository to your pom.xml or link it as remote repository to nexus is quite sufficient.
Check README.MD for the details.

~~(To be fair I haven't tried the resolution via GitHub for quite some time.)~~
I just validate that the resolution via GitHub works. At least when configured as repository in pom.xml. Maybe you could try to add the repository to your nexus and give feedback if this is a usable solution for that use case.

If you see any additional benefit feel free to describe than I might have another look for publishing to maven central.
